services:
  gost:
    image: ginuerzh/gost
    container_name: gost
    restart: unless-stopped
    networks:
      macvlan:
        ipv4_address: 192.168.1.90
    command:
      -L=:1080?udp=true -F=192.168.1.254:7890
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
    volumes:
      - /opt/docker_volume/qbittorrent/config:/config
      - /opt/docker_volume/qbittorrent/downloads:/downloads
    networks:
      macvlan:
        ipv4_address: 192.168.1.89
#    depends_on:
#      - gost
#    links:
#      - gost
networks:
  macvlan:
    name: iMacvlan
    driver: macvlan
    driver_opts:
      parent: ens33
      macvlan_mode: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.254

