services:
  gost:
    image: ginuerzh/gost
    container_name: gost
    restart: unless-stopped
    networks:
      macvlan:
        ipv4_address: 192.168.1.90
    command:
      -L=:1080?udp=true -F=192.168.1.254:7890
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    environment:
#      - PUID=1000
#      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=443
    volumes:
      - '/mnt/NFS_Share/iDownload:/downloads'
      - '/mnt/NFS_Share/DockerPV/qbittorrent/config:/config'
    networks:
      macvlan:
        ipv4_address: 192.168.1.89
#    depends_on:
#      - gost
#    links:
#      - gost
  baidunetdisk:
    ports:
      - '5800:5800'
      - '5801:5900'
    volumes:
      - '/mnt/NFS_Share/DockerPV/baidunetdisk:/config'
      - '/mnt/NFS_Share/iDownload:/download'
    image: johngong/baidunetdisk:latest
    restart: unless-stopped
    container_name: baidunetdisk
#  samba:
#     ports:
#       - '139:139'
#       - '445:445'
#      volumes:
#        - '/mnt/NFS_Share/iDownload:/Share'
#      environment:
#        - USERID=1000
#        - GROUPID=1000
#        - TZ=Asia/Shanghai
#      image: dperson/samba
#      restart: unless-stopped
#      container_name: samba
#      network_mode: host
#      command: '-g "client min protocol = NT1" -s "iShare;/Share;yes;no;yes" -p -n'
  gerbera:
    image: gerbera/gerbera
    restart: unless-stopped
    container_name: gerbera
    network_mode: host
    volumes:
      - '/mnt/NFS_Share/iDownload:/content:ro'
      - '/mnt/NFS_Share/DockerPV/gerbera:/var/run/gerbera'
networks:
  macvlan:
    name: iMacvlan
    driver: macvlan
    driver_opts:
      parent: ens18
      macvlan_mode: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.254
#volumes:
#  ShareVolume:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: /opt/docker_volume/samba
