services:
  samba:
    ports:
      - '139:139'
      - '445:445'
    volumes:
      - '/mnt/NFS_Share/iDownload:/Share'
    environment:
      - USERID=1000
      - GROUPID=1000
      - TZ=Asia/Shanghai
    image: dperson/samba
    restart: unless-stopped
    container_name: samba
    network_mode: host
    command: '-g "client min protocol = NT1" -s "iShare;/Share;yes;no;yes" -p -n'

