services:
    subconverter:
        ports:
            - '25500:25500'
            - '25501:80'
        image: tindy2013/subconverter:latest
        restart: unless-stopped
        container_name: subconverter
    subweb:
        image: careywong/subweb:latest
        restart: unless-stopped
        container_name: subweb
        network_mode: service:subconverter
        depends_on:
          - subconverter

